apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: celrun-with-context-
  labels:
    tekton.dev/pipelineRun: test-pr
spec:
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: VariableStore
    name: example-0
  params:
    - name: job-priority
      value: "medium"
